### ISSUE TITLE
Some sensor error after the core update (2023.11.0)

### ISSUE THREAD

**Issue by kovacsla** [mauro-midolo/homeassistant_electrolux_status#143] opened 2023-11-02 18:55 UTC
After the HA core update (2023.11.0) some sensor unavailable state.

2023-11-02 18:09:20.942 ERROR (MainThread) [homeassistant.components.sensor] Error adding entities for domain sensor with platform electrolux_status
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 507, in async_add_entities
    await asyncio.gather(*tasks)
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 752, in _async_add_entity
    await entity.add_to_platform_finish()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 1021, in add_to_platform_finish
    await self.async_internal_added_to_hass()
  File "/usr/src/homeassistant/homeassistant/components/sensor/__init__.py", line 279, in async_internal_added_to_hass
    raise HomeAssistantError(
homeassistant.exceptions.HomeAssistantError: Entity sensor.electrolux_moso_masa_wd1_remotecontrol cannot be added as the entity category is set to config
2023-11-02 18:09:20.957 ERROR (MainThread) [homeassistant.components.sensor] Error while setting up electrolux_status platform for sensor
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 367, in _async_setup_platform
    await asyncio.gather(*pending)
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 507, in async_add_entities
    await asyncio.gather(*tasks)
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 752, in _async_add_entity
    await entity.add_to_platform_finish()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 1021, in add_to_platform_finish
    await self.async_internal_added_to_hass()
  File "/usr/src/homeassistant/homeassistant/components/sensor/__init__.py", line 279, in async_internal_added_to_hass
    raise HomeAssistantError(
homeassistant.exceptions.HomeAssistantError: Entity sensor.electrolux_moso_masa_wd1_remotecontrol cannot be added as the entity category is set to config

**Comment by wgumaa** [comment] 2023-11-02 20:41
Yes the same problem for my Electrolux washing machine.

Here is a list of what is unavailable: 

- Default Extra Rinse
- Programmes
- Remote Control
- Spin Speed (rpm)
- Starts in
-  Steam Level
- Temperature
- Time Manager

Rest looks ok.

**Comment by kovacsla** [comment] 2023-11-03 09:01
I have Electrolux Perfect Care 900 
Here is list of what is unavailable:

sensor.electrolux_perfect_care_900_wd1_**remotecontrol**; Electrolux Care Integration
sensor.electrolux_perfect_care_900_wd1_**starttime**; Electrolux Care Integration
sensor.electrolux_perfect_care_900_wd1_**analogtemperature**; Electrolux Care Integration
sensor.electrolux_perfect_care_900_wd1_**defaultextrarinse**; Electrolux Care Integration
sensor.electrolux_perfect_care_900_wd1_**steamvalue** ;Electrolux Care Integration
sensor.electrolux_perfect_care_900_wd1_**eluxtimemanagerlevel**; Electrolux Care Integration
sensor.electrolux_perfect_care_900_wd1_**analogspinspeed**; Electrolux Care Integration
sensor.electrolux_perfect_care_900_wd1_**dryingtime** ;Electrolux Care Integration
sensor.electrolux_perfect_care_900_wd1_**humiditytarget**; Electrolux Care Integration
sensor.electrolux_perfect_care_900_wd1_**programuid**; Electrolux Care Integration

**Comment by abdonkov** [comment] 2023-11-05 10:06
I had the same problem for a Washing Machine, Dryer and an Oven. And happened exactly after update of home assistant. Two times, because I have watchtower that updates it automatically.

**I found a silly fix however.** If you open the editor for the Unavailable Entity and change something, in my case I just added an Icon it because available again.

So maybe something in a new version of Home Assistant doesn't play nice with this integration, not really sure. Will see if after the next docker image update, the same thing happens :)

**Comment by wgumaa** [comment] 2023-11-05 11:05
@abdonkov, I just tried your suggestion of changing icons and it worked 😂. 
I still think it needs fix though!

**Comment by allistermaguire** [comment] 2023-11-05 23:22
Is this resolved in Hass version 2023.11.1?

**Comment by allistermaguire** [comment] 2023-11-05 23:38
Caused by https://github.com/home-assistant/core/pull/101471. It looks like `EntityCategory.CONFIG` is just used to group them, it shouldn't be difficult to fix.

**Closed** 2023-11-06 07:52 UTC
